/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Ameer Studio (https://sketchfab.com/uchiha.321abc)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/tesla-2018-model-3-5ef9b845aaf44203b6d04e2c677e444f
title: Tesla 2018 Model 3
*/

import * as THREE from 'three'
import { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'
import { useSnapshot } from 'valtio'
import { CarProps } from '../App'

type GLTFResult = GLTF & {
  nodes: {
    hub_rb_hub_rb0_0: THREE.Mesh
    hub_lb_hub_rb0_0: THREE.Mesh
    hub_rf_hub_rf0_0: THREE.Mesh
    hub_rf_hub_rf1_0: THREE.Mesh
    hub_lf_hub_rf0_0: THREE.Mesh
    hub_lf_hub_rf1_0: THREE.Mesh
    dvorright_dvorright0_0: THREE.Mesh
    dvorleft_dvorright0_0: THREE.Mesh
    movsteer_10_movsteer_101_0: THREE.Mesh
    movsteer_10_movsteer_100_0: THREE.Mesh
    movsteer_10_dvorright0_0: THREE.Mesh
    JUST_BLACK001_JUST_BLACK0_0: THREE.Mesh
    JUST_BLACK_JUST_BLACK0_0: THREE.Mesh
    body_primary_0: THREE.Mesh
    bodysills_primary001_0: THREE.Mesh
    _plastic_black_124_black_lights0_0: THREE.Mesh
    _satin_black_134_black_lights0_0: THREE.Mesh
    pantulans_pantulans0_0: THREE.Mesh
    rear_lights_right_rear_light_0: THREE.Mesh
    light_breake_breaklight_l_0: THREE.Mesh
    back_chrome_light_back_chrome_light0_0: THREE.Mesh
    chrome_foglight_r_foglight_r_0: THREE.Mesh
    chrome_foglight_l_foglight_l_0: THREE.Mesh
    chrome_Lights_head_l_right_front_light_0: THREE.Mesh
    chrome_Lights_head_l_left_front_light_0: THREE.Mesh
    chrome_movsteer_101_0: THREE.Mesh
    breake_int_breaklight_l_0: THREE.Mesh
    aluminium_light_aluminium_light0_0: THREE.Mesh
    tembus_red_tembus_red0_0: THREE.Mesh
    interiorlights_light_night_0: THREE.Mesh
    turn_indicat_l_indicator_lf_0: THREE.Mesh
    turn_indicat_r_indicator_rf_0: THREE.Mesh
    black_lights_black_lights0_0: THREE.Mesh
    hitam_dvorright0_0: THREE.Mesh
    hitam001_dvorright0_0: THREE.Mesh
    hitam002_hitam0_0: THREE.Mesh
    Plastic_Plastic0_0: THREE.Mesh
    belt_belt0_0: THREE.Mesh
    black_black_lights0_0: THREE.Mesh
    satin_red_satin_red0_0: THREE.Mesh
    paint_black_dvorright0_0: THREE.Mesh
    cahrome_movsteer_101_0: THREE.Mesh
    suspensi_suspensi0_0: THREE.Mesh
    suspensi_suspensi1_0: THREE.Mesh
    chrome__movsteer_101_0: THREE.Mesh
    chrome1_movsteer_101_0: THREE.Mesh
    chrome2_movsteer_101_0: THREE.Mesh
    hitam003_dvorright0_0: THREE.Mesh
    hitam004_dvorright0_0: THREE.Mesh
    aluminium_movsteer_101_0: THREE.Mesh
    hitam005_Plastic0_0: THREE.Mesh
    hitam006_black_lights0_0: THREE.Mesh
    texture_Leather_movsteer_100_0: THREE.Mesh
    texture_Leather001_movsteer_100_0: THREE.Mesh
    aluminium2_aluminium20_0: THREE.Mesh
    frunkplastic_dvorright0_0: THREE.Mesh
    Putih_Putih0_0: THREE.Mesh
    whiteleather_Putih0_0: THREE.Mesh
    Putih001_Putih0_0: THREE.Mesh
    Putih002_Putih0_0: THREE.Mesh
    Carpet_Carpet0_0: THREE.Mesh
    black001_Plastic0_0: THREE.Mesh
    black002_Plastic0_0: THREE.Mesh
    black003_black_lights0_0: THREE.Mesh
    black004_JUST_BLACK0_0: THREE.Mesh
    black005_black_lights0_0: THREE.Mesh
    Carpet_Light_Carpet_Light0_0: THREE.Mesh
    chromeBELT_movsteer_101_0: THREE.Mesh
    suspensi2_suspensi0_0: THREE.Mesh
    suspensi2_suspensi1_0: THREE.Mesh
    texture_Buttons_texture_Buttons0_0: THREE.Mesh
    LCDs_LCDs0_0: THREE.Mesh
    Leather_white_Seat_Leather_white0_0: THREE.Mesh
    Seat_Leather_white_Seat_Leather_white0_0: THREE.Mesh
    mirror_inside_mirror_inside0_0: THREE.Mesh
    base_dvorright0_0: THREE.Mesh
    glass_glass0_0: THREE.Mesh
    glass_glass1_0: THREE.Mesh
    chassis_chassis0_0: THREE.Mesh
    boot_primary_0: THREE.Mesh
    platnomor_JUST_BLACK0_0: THREE.Mesh
    platnomor_platnomor1_0: THREE.Mesh
    platnomor_hitam0_0: THREE.Mesh
    platnomor_platnomor2_0: THREE.Mesh
    chrome001_movsteer_101_0: THREE.Mesh
    light_turn_rr_boot_indicator_rr_0: THREE.Mesh
    light_turn_lr_boot_indicator_lr_0: THREE.Mesh
    chrome_light_back_chrome_light0_0: THREE.Mesh
    rear_lightsr_right_rear_light_0: THREE.Mesh
    rear_lightsl_left_rear_light_0: THREE.Mesh
    lightrevese_boot_revlight_L_0: THREE.Mesh
    tembus_boot_ok_tembus_red0_0: THREE.Mesh
    black_boot_black_lights0_0: THREE.Mesh
    door_lf_ok_primary_0: THREE.Mesh
    door_lf_JUST_BLACK0_0: THREE.Mesh
    door_lf_texture_Buttons0_0: THREE.Mesh
    door_lf_movsteer_101_0: THREE.Mesh
    door_lf_movsteer_100_0: THREE.Mesh
    door_lf_Putih0_0: THREE.Mesh
    door_lf_Plastic0_0: THREE.Mesh
    door_lf_aluminium20_0: THREE.Mesh
    door_lf_dvorright0_0: THREE.Mesh
    door_lf_door_lf0_0: THREE.Mesh
    door_lf_door_lf5_0: THREE.Mesh
    door_lf_glass0_0: THREE.Mesh
    door_lf_mirror_inside0_0: THREE.Mesh
    door_lf_primary_0: THREE.Mesh
    door_lf_primary002_0: THREE.Mesh
    door_lr_ok_primary_0: THREE.Mesh
    door_lr_JUST_BLACK0_0: THREE.Mesh
    door_lr_texture_Buttons0_0: THREE.Mesh
    door_lr_primary004_0: THREE.Mesh
    door_lr_movsteer_101_0: THREE.Mesh
    door_lr_movsteer_100_0: THREE.Mesh
    door_lr_Putih0_0: THREE.Mesh
    door_lr_Plastic0_0: THREE.Mesh
    door_lr_aluminium20_0: THREE.Mesh
    door_lr_dvorright0_0: THREE.Mesh
    door_lr_glass0_0: THREE.Mesh
    door_lr_primary_0: THREE.Mesh
    door_lr_primary002_0: THREE.Mesh
    door_rf_ok_primary_0: THREE.Mesh
    door_rf_JUST_BLACK0_0: THREE.Mesh
    door_rf_texture_Buttons0_0: THREE.Mesh
    door_rf_movsteer_101_0: THREE.Mesh
    door_rf_movsteer_100_0: THREE.Mesh
    door_rf_Putih0_0: THREE.Mesh
    door_rf_Plastic0_0: THREE.Mesh
    door_rf_aluminium20_0: THREE.Mesh
    door_rf_dvorright0_0: THREE.Mesh
    door_rf_door_lf0_0: THREE.Mesh
    door_rf_glass0_0: THREE.Mesh
    door_rf_mirror_inside0_0: THREE.Mesh
    door_rf_primary_0: THREE.Mesh
    door_rf_primary002_0: THREE.Mesh
    door_rr_ok_primary002_0: THREE.Mesh
    door_rr_JUST_BLACK0_0: THREE.Mesh
    door_rr_texture_Buttons0_0: THREE.Mesh
    door_rr_movsteer_101_0: THREE.Mesh
    door_rr_movsteer_100_0: THREE.Mesh
    door_rr_Putih0_0: THREE.Mesh
    door_rr_Plastic0_0: THREE.Mesh
    door_rr_aluminium20_0: THREE.Mesh
    door_rr_dvorright0_0: THREE.Mesh
    door_rr_glass0_0: THREE.Mesh
    door_rr_primary_0: THREE.Mesh
    door_rr_primary002_0: THREE.Mesh
    windscreen_ok_glass0_0: THREE.Mesh
    chrome002_back_chrome_light0_0: THREE.Mesh
    foglights_r_foglight_r_0: THREE.Mesh
    foglights_l_foglight_l_0: THREE.Mesh
    indicator_lights_r_indicator_rf_0: THREE.Mesh
    indicator_lights_l_indicator_lf_0: THREE.Mesh
    tembus_depan_ok_tembus_red0_0: THREE.Mesh
    front_black_front_black0_0: THREE.Mesh
    front_bumper_ok_primary_0: THREE.Mesh
    rear_bumper_ok_primary_0: THREE.Mesh
    light_pantulan_light_pantulan0_0: THREE.Mesh
    tembus_belakang_tembus_red0_0: THREE.Mesh
    rear_bumper_movsteer_101_0: THREE.Mesh
    chrome_bonnet_ok_movsteer_101_0: THREE.Mesh
    bonnet_ok_primary_0: THREE.Mesh
    wheels_wheels2_0: THREE.Mesh
    wheels_wheels0_0: THREE.Mesh
    wheels_wheels1_0: THREE.Mesh
    wheels_movsteer_101_0: THREE.Mesh
    wheels_wheels3_0: THREE.Mesh
    wheels_wheels4_0: THREE.Mesh
    wheels_wheels6_0: THREE.Mesh
    wheels001_wheels2_0: THREE.Mesh
    wheels001_wheels0_0: THREE.Mesh
    wheels001_wheels1_0: THREE.Mesh
    wheels001_movsteer_101_0: THREE.Mesh
    wheels001_wheels3_0: THREE.Mesh
    wheels001_wheels4_0: THREE.Mesh
    wheels001_wheels6_0: THREE.Mesh
  }
  materials: {
    ['hub_rb.0']: THREE.MeshStandardMaterial
    ['hub_rf.0']: THREE.MeshStandardMaterial
    ['hub_rf.1']: THREE.MeshStandardMaterial
    ['dvorright.0']: THREE.MeshStandardMaterial
    ['movsteer_1.0.1']: THREE.MeshStandardMaterial
    ['movsteer_1.0.0']: THREE.MeshStandardMaterial
    ['JUST_BLACK.0']: THREE.MeshStandardMaterial
    primary: THREE.MeshStandardMaterial
    ['primary.001']: THREE.MeshStandardMaterial
    ['black_lights.0']: THREE.MeshStandardMaterial
    ['pantulans.0']: THREE.MeshStandardMaterial
    right_rear_light: THREE.MeshStandardMaterial
    breaklight_l: THREE.MeshStandardMaterial
    ['back_chrome_light.0']: THREE.MeshStandardMaterial
    foglight_r: THREE.MeshStandardMaterial
    foglight_l: THREE.MeshStandardMaterial
    right_front_light: THREE.MeshStandardMaterial
    left_front_light: THREE.MeshStandardMaterial
    ['aluminium_light.0']: THREE.MeshStandardMaterial
    ['tembus_red.0']: THREE.MeshStandardMaterial
    light_night: THREE.MeshStandardMaterial
    indicator_lf: THREE.MeshStandardMaterial
    indicator_rf: THREE.MeshStandardMaterial
    ['hitam.0']: THREE.MeshStandardMaterial
    ['Plastic.0']: THREE.MeshStandardMaterial
    ['belt.0']: THREE.MeshStandardMaterial
    ['satin_red.0']: THREE.MeshStandardMaterial
    ['suspensi.0']: THREE.MeshStandardMaterial
    ['suspensi.1']: THREE.MeshStandardMaterial
    ['aluminium2.0']: THREE.MeshStandardMaterial
    ['Putih.0']: THREE.MeshStandardMaterial
    ['Carpet.0']: THREE.MeshStandardMaterial
    ['Carpet_Light.0']: THREE.MeshStandardMaterial
    ['texture_Buttons.0']: THREE.MeshStandardMaterial
    ['LCDs.0']: THREE.MeshStandardMaterial
    ['Seat_Leather_white.0']: THREE.MeshStandardMaterial
    ['mirror_inside.0']: THREE.MeshStandardMaterial
    ['glass.0']: THREE.MeshStandardMaterial
    ['glass.1']: THREE.MeshStandardMaterial
    ['chassis.0']: THREE.MeshStandardMaterial
    ['platnomor.1']: THREE.MeshStandardMaterial
    ['platnomor.2']: THREE.MeshStandardMaterial
    indicator_rr: THREE.MeshStandardMaterial
    indicator_lr: THREE.MeshStandardMaterial
    left_rear_light: THREE.MeshStandardMaterial
    revlight_L: THREE.MeshStandardMaterial
    ['door_lf.0']: THREE.MeshStandardMaterial
    ['door_lf.5']: THREE.MeshStandardMaterial
    ['primary.002']: THREE.MeshStandardMaterial
    ['primary.004']: THREE.MeshStandardMaterial
    ['front_black.0']: THREE.MeshStandardMaterial
    ['light_pantulan.0']: THREE.MeshStandardMaterial
    ['wheels.2']: THREE.MeshStandardMaterial
    ['wheels.0']: THREE.MeshStandardMaterial
    ['wheels.1']: THREE.MeshStandardMaterial
    ['wheels.3']: THREE.MeshStandardMaterial
    ['wheels.4']: THREE.MeshStandardMaterial
    ['wheels.6']: THREE.MeshStandardMaterial
  }
}

export default function Model(props: any)  {
  const group = useRef<THREE.Group>();
  const { nodes, materials } = useGLTF('/scene.glb') as GLTFResult
  const snap = useSnapshot(props.myState) as CarProps;
  if (snap.cars[props.myState.current] !== 'Scene') {
    return null;
  };
  return (
    <group name="Scene" visible={props.visibility} ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 0.4, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={1.3}>
            <group position={[0.9, -1.45, -0.37]}>
              <mesh geometry={nodes.hub_rb_hub_rb0_0.geometry} material={materials['hub_rb.0']} />
            </group>
            <group position={[-0.9, -1.45, -0.37]}>
              <mesh geometry={nodes.hub_lb_hub_rb0_0.geometry} material={materials['hub_rb.0']} />
            </group>
            <group position={[0.92, 1.76, -0.37]}>
              <mesh geometry={nodes.hub_rf_hub_rf0_0.geometry} material={materials['hub_rf.0']} />
              <mesh geometry={nodes.hub_rf_hub_rf1_0.geometry} material={materials['hub_rf.1']} />
            </group>
            <group position={[-0.92, 1.76, -0.37]}>
              <mesh geometry={nodes.hub_lf_hub_rf0_0.geometry} material={materials['hub_rf.0']} />
              <mesh geometry={nodes.hub_lf_hub_rf1_0.geometry} material={materials['hub_rf.1']} />
            </group>
            <group position={[-0.08, 1.6, 0.18]} rotation={[0.96, 0, 0]}>
              <mesh geometry={nodes.dvorright_dvorright0_0.geometry} material={materials['dvorright.0']} />
              <group position={[-0.62, -0.08, 0.17]} rotation={[0.13, 0, 0]}>
                <mesh geometry={nodes.dvorleft_dvorright0_0.geometry} material={materials['dvorright.0']} />
              </group>
            </group>
            <group position={[-0.47, 0.61, 0.18]} rotation={[-0.31, 0, 0]}>
              <mesh geometry={nodes.movsteer_10_movsteer_101_0.geometry} material={materials['movsteer_1.0.1']} />
              <mesh geometry={nodes.movsteer_10_movsteer_100_0.geometry} material={materials['movsteer_1.0.0']} />
              <mesh geometry={nodes.movsteer_10_dvorright0_0.geometry} material={materials['dvorright.0']} />
            </group>
            <group position={[0, 1.77, -0.36]}>
              <group position={[0, -1.77, 0.36]}>
                <mesh geometry={nodes.JUST_BLACK001_JUST_BLACK0_0.geometry} material={materials['JUST_BLACK.0']} />
                <mesh geometry={nodes.JUST_BLACK_JUST_BLACK0_0.geometry} material={materials['JUST_BLACK.0']} />
              </group>
              <group position={[0, -1.77, 0.36]}>
                <mesh geometry={nodes.body_primary_0.geometry} material={materials.primary} />
              </group>
              <group position={[0, -1.77, 0.36]}>
                <mesh geometry={nodes.bodysills_primary001_0.geometry} material={materials['primary.001']} />
              </group>
              <group position={[0, -1.77, 0.36]}>
                <mesh geometry={nodes._plastic_black_124_black_lights0_0.geometry} material={materials['black_lights.0']} />
                <mesh geometry={nodes._satin_black_134_black_lights0_0.geometry} material={materials['black_lights.0']} />
                <mesh geometry={nodes.pantulans_pantulans0_0.geometry} material={materials['pantulans.0']} />
                <mesh geometry={nodes.rear_lights_right_rear_light_0.geometry} material={materials.right_rear_light} />
                <mesh geometry={nodes.light_breake_breaklight_l_0.geometry} material={materials.breaklight_l} />
                <mesh geometry={nodes.back_chrome_light_back_chrome_light0_0.geometry} material={materials['back_chrome_light.0']} />
                <mesh geometry={nodes.chrome_foglight_r_foglight_r_0.geometry} material={materials.foglight_r} />
                <mesh geometry={nodes.chrome_foglight_l_foglight_l_0.geometry} material={materials.foglight_l} />
                <mesh geometry={nodes.chrome_Lights_head_l_right_front_light_0.geometry} material={materials.right_front_light} />
                <mesh geometry={nodes.chrome_Lights_head_l_left_front_light_0.geometry} material={materials.left_front_light} />
                <mesh geometry={nodes.chrome_movsteer_101_0.geometry} material={materials['movsteer_1.0.1']} />
                <mesh geometry={nodes.breake_int_breaklight_l_0.geometry} material={materials.breaklight_l} />
                <mesh geometry={nodes.aluminium_light_aluminium_light0_0.geometry} material={materials['aluminium_light.0']} />
                <mesh geometry={nodes.tembus_red_tembus_red0_0.geometry} material={materials['tembus_red.0']} />
                <mesh geometry={nodes.interiorlights_light_night_0.geometry} material={materials.light_night} />
                <mesh geometry={nodes.turn_indicat_l_indicator_lf_0.geometry} material={materials.indicator_lf} />
                <mesh geometry={nodes.turn_indicat_r_indicator_rf_0.geometry} material={materials.indicator_rf} />
                <mesh geometry={nodes.black_lights_black_lights0_0.geometry} material={materials['black_lights.0']} />
              </group>
              <group position={[0, -1.77, 0.36]}>
                <mesh geometry={nodes.hitam_dvorright0_0.geometry} material={materials['dvorright.0']} />
                <mesh geometry={nodes.hitam001_dvorright0_0.geometry} material={materials['dvorright.0']} />
                <mesh geometry={nodes.hitam002_hitam0_0.geometry} material={materials['hitam.0']} />
                <mesh geometry={nodes.Plastic_Plastic0_0.geometry} material={materials['Plastic.0']} />
                <mesh geometry={nodes.belt_belt0_0.geometry} material={materials['belt.0']} />
                <mesh geometry={nodes.black_black_lights0_0.geometry} material={materials['black_lights.0']} />
                <mesh geometry={nodes.satin_red_satin_red0_0.geometry} material={materials['satin_red.0']} />
                <mesh geometry={nodes.paint_black_dvorright0_0.geometry} material={materials['dvorright.0']} />
                <mesh geometry={nodes.cahrome_movsteer_101_0.geometry} material={materials['movsteer_1.0.1']} />
                <mesh geometry={nodes.suspensi_suspensi0_0.geometry} material={materials['suspensi.0']} />
                <mesh geometry={nodes.suspensi_suspensi1_0.geometry} material={materials['suspensi.1']} />
                <mesh geometry={nodes.chrome__movsteer_101_0.geometry} material={materials['movsteer_1.0.1']} />
                <mesh geometry={nodes.chrome1_movsteer_101_0.geometry} material={materials['movsteer_1.0.1']} />
                <mesh geometry={nodes.chrome2_movsteer_101_0.geometry} material={materials['movsteer_1.0.1']} />
                <mesh geometry={nodes.hitam003_dvorright0_0.geometry} material={materials['dvorright.0']} />
                <mesh geometry={nodes.hitam004_dvorright0_0.geometry} material={materials['dvorright.0']} />
                <mesh geometry={nodes.aluminium_movsteer_101_0.geometry} material={materials['movsteer_1.0.1']} />
                <mesh geometry={nodes.hitam005_Plastic0_0.geometry} material={materials['Plastic.0']} />
                <mesh geometry={nodes.hitam006_black_lights0_0.geometry} material={materials['black_lights.0']} />
                <mesh geometry={nodes.texture_Leather_movsteer_100_0.geometry} material={materials['movsteer_1.0.0']} />
                <mesh geometry={nodes.texture_Leather001_movsteer_100_0.geometry} material={materials['movsteer_1.0.0']} />
                <mesh geometry={nodes.aluminium2_aluminium20_0.geometry} material={materials['aluminium2.0']} />
                <mesh geometry={nodes.frunkplastic_dvorright0_0.geometry} material={materials['dvorright.0']} />
                <mesh geometry={nodes.Putih_Putih0_0.geometry} material={materials['Putih.0']} />
                <mesh geometry={nodes.whiteleather_Putih0_0.geometry} material={materials['Putih.0']} />
                <mesh geometry={nodes.Putih001_Putih0_0.geometry} material={materials['Putih.0']} />
                <mesh geometry={nodes.Putih002_Putih0_0.geometry} material={materials['Putih.0']} />
                <mesh geometry={nodes.Carpet_Carpet0_0.geometry} material={materials['Carpet.0']} />
                <mesh geometry={nodes.black001_Plastic0_0.geometry} material={materials['Plastic.0']} />
                <mesh geometry={nodes.black002_Plastic0_0.geometry} material={materials['Plastic.0']} />
                <mesh geometry={nodes.black003_black_lights0_0.geometry} material={materials['black_lights.0']} />
                <mesh geometry={nodes.black004_JUST_BLACK0_0.geometry} material={materials['JUST_BLACK.0']} />
                <mesh geometry={nodes.black005_black_lights0_0.geometry} material={materials['black_lights.0']} />
                <mesh geometry={nodes.Carpet_Light_Carpet_Light0_0.geometry} material={materials['Carpet_Light.0']} />
                <mesh geometry={nodes.chromeBELT_movsteer_101_0.geometry} material={materials['movsteer_1.0.1']} />
                <mesh geometry={nodes.suspensi2_suspensi0_0.geometry} material={materials['suspensi.0']} />
                <mesh geometry={nodes.suspensi2_suspensi1_0.geometry} material={materials['suspensi.1']} />
                <mesh geometry={nodes.texture_Buttons_texture_Buttons0_0.geometry} material={materials['texture_Buttons.0']} />
                <mesh geometry={nodes.LCDs_LCDs0_0.geometry} material={materials['LCDs.0']} />
                <mesh geometry={nodes.Leather_white_Seat_Leather_white0_0.geometry} material={materials['Seat_Leather_white.0']} />
                <mesh material-color={snap.items.interior} geometry={nodes.Seat_Leather_white_Seat_Leather_white0_0.geometry} material={materials['Seat_Leather_white.0']} />
                <mesh geometry={nodes.mirror_inside_mirror_inside0_0.geometry} material={materials['mirror_inside.0']} />
                <mesh geometry={nodes.base_dvorright0_0.geometry} material={materials['dvorright.0']} />
              </group>
              <group position={[0, -1.04, 0.93]}>
                <mesh geometry={nodes.glass_glass0_0.geometry} material={materials['glass.0']} />
                <mesh geometry={nodes.glass_glass1_0.geometry} material={materials['glass.1']} />
              </group>
              <mesh geometry={nodes.chassis_chassis0_0.geometry} material={materials['chassis.0']} />
            </group>
            <group position={[0, -1.69, 0.6]}>
              <mesh geometry={nodes.boot_primary_0.geometry} material={materials.primary} />
              <mesh geometry={nodes.platnomor_JUST_BLACK0_0.geometry} material={materials['JUST_BLACK.0']} />
              <mesh geometry={nodes.platnomor_platnomor1_0.geometry} material={materials['platnomor.1']} />
              <mesh geometry={nodes.platnomor_hitam0_0.geometry} material={materials['hitam.0']} />
              <mesh geometry={nodes.platnomor_platnomor2_0.geometry} material={materials['platnomor.2']} />
              <mesh geometry={nodes.chrome001_movsteer_101_0.geometry} material={materials['movsteer_1.0.1']} />
              <mesh geometry={nodes.light_turn_rr_boot_indicator_rr_0.geometry} material={materials.indicator_rr} />
              <mesh geometry={nodes.light_turn_lr_boot_indicator_lr_0.geometry} material={materials.indicator_lr} />
              <mesh geometry={nodes.chrome_light_back_chrome_light0_0.geometry} material={materials['back_chrome_light.0']} />
              <mesh geometry={nodes.rear_lightsr_right_rear_light_0.geometry} material={materials.right_rear_light} />
              <mesh geometry={nodes.rear_lightsl_left_rear_light_0.geometry} material={materials.left_rear_light} />
              <mesh geometry={nodes.lightrevese_boot_revlight_L_0.geometry} material={materials.revlight_L} />
              <mesh geometry={nodes.tembus_boot_ok_tembus_red0_0.geometry} material={materials['tembus_red.0']} />
              <mesh geometry={nodes.black_boot_black_lights0_0.geometry} material={materials['black_lights.0']} />
            </group>
            {/* <group position={[-1.01, 1.18, -0.06]} visible={props.visibility} >
              <mesh geometry={nodes.door_lf_ok_primary_0.geometry} material={materials.primary} />
              <mesh geometry={nodes.door_lf_JUST_BLACK0_0.geometry} material={materials['JUST_BLACK.0']} />
              <mesh geometry={nodes.door_lf_texture_Buttons0_0.geometry} material={materials['texture_Buttons.0']} />
              <mesh geometry={nodes.door_lf_movsteer_101_0.geometry} material={materials['movsteer_1.0.1']} />
              <mesh geometry={nodes.door_lf_movsteer_100_0.geometry} material={materials['movsteer_1.0.0']} />
              <mesh geometry={nodes.door_lf_Putih0_0.geometry} material={materials['Putih.0']} />
              <mesh geometry={nodes.door_lf_Plastic0_0.geometry} material={materials['Plastic.0']} />
              <mesh geometry={nodes.door_lf_aluminium20_0.geometry} material={materials['aluminium2.0']} />
              <mesh geometry={nodes.door_lf_dvorright0_0.geometry} material={materials['dvorright.0']} />
              <mesh geometry={nodes.door_lf_door_lf0_0.geometry} material={materials['door_lf.0']} />
              <mesh geometry={nodes.door_lf_door_lf5_0.geometry} material={materials['door_lf.5']} />
              <mesh geometry={nodes.door_lf_glass0_0.geometry} material={materials['glass.0']} />
              <mesh geometry={nodes.door_lf_mirror_inside0_0.geometry} material={materials['mirror_inside.0']} />
              <mesh geometry={nodes.door_lf_primary_0.geometry} material={materials.primary} />
              <mesh geometry={nodes.door_lf_primary002_0.geometry} material={materials['primary.002']} />
            </group> */}
            <group position={[-1.03, -0.13, -0.06]}>
              <mesh geometry={nodes.door_lr_ok_primary_0.geometry} material={materials.primary} />
              <mesh geometry={nodes.door_lr_JUST_BLACK0_0.geometry} material={materials['JUST_BLACK.0']} />
              <mesh geometry={nodes.door_lr_texture_Buttons0_0.geometry} material={materials['texture_Buttons.0']} />
              <mesh geometry={nodes.door_lr_primary004_0.geometry} material={materials['primary.004']} />
              <mesh geometry={nodes.door_lr_movsteer_101_0.geometry} material={materials['movsteer_1.0.1']} />
              <mesh geometry={nodes.door_lr_movsteer_100_0.geometry} material={materials['movsteer_1.0.0']} />
              <mesh geometry={nodes.door_lr_Putih0_0.geometry} material={materials['Putih.0']} />
              <mesh geometry={nodes.door_lr_Plastic0_0.geometry} material={materials['Plastic.0']} />
              <mesh geometry={nodes.door_lr_aluminium20_0.geometry} material={materials['aluminium2.0']} />
              <mesh geometry={nodes.door_lr_dvorright0_0.geometry} material={materials['dvorright.0']} />
              <mesh geometry={nodes.door_lr_glass0_0.geometry} material={materials['glass.0']} />
              <mesh geometry={nodes.door_lr_primary_0.geometry} material={materials.primary} />
              <mesh geometry={nodes.door_lr_primary002_0.geometry} material={materials['primary.002']} />
            </group>
            <group position={[1.01, 1.18, -0.06]}>
              <mesh geometry={nodes.door_rf_ok_primary_0.geometry} material={materials.primary} />
              <mesh geometry={nodes.door_rf_JUST_BLACK0_0.geometry} material={materials['JUST_BLACK.0']} />
              <mesh geometry={nodes.door_rf_texture_Buttons0_0.geometry} material={materials['texture_Buttons.0']} />
              <mesh geometry={nodes.door_rf_movsteer_101_0.geometry} material={materials['movsteer_1.0.1']} />
              <mesh geometry={nodes.door_rf_movsteer_100_0.geometry} material={materials['movsteer_1.0.0']} />
              <mesh geometry={nodes.door_rf_Putih0_0.geometry} material={materials['Putih.0']} />
              <mesh geometry={nodes.door_rf_Plastic0_0.geometry} material={materials['Plastic.0']} />
              <mesh geometry={nodes.door_rf_aluminium20_0.geometry} material={materials['aluminium2.0']} />
              <mesh geometry={nodes.door_rf_dvorright0_0.geometry} material={materials['dvorright.0']} />
              <mesh geometry={nodes.door_rf_door_lf0_0.geometry} material={materials['door_lf.0']} />
              <mesh geometry={nodes.door_rf_glass0_0.geometry} material={materials['glass.0']} />
              <mesh geometry={nodes.door_rf_mirror_inside0_0.geometry} material={materials['mirror_inside.0']} />
              <mesh geometry={nodes.door_rf_primary_0.geometry} material={materials.primary} />
              <mesh geometry={nodes.door_rf_primary002_0.geometry} material={materials['primary.002']} />
            </group>
            <group position={[1.03, -0.13, -0.06]}>
              <mesh geometry={nodes.door_rr_ok_primary002_0.geometry} material={materials['primary.002']} />
              <mesh geometry={nodes.door_rr_JUST_BLACK0_0.geometry} material={materials['JUST_BLACK.0']} />
              <mesh geometry={nodes.door_rr_texture_Buttons0_0.geometry} material={materials['texture_Buttons.0']} />
              <mesh geometry={nodes.door_rr_movsteer_101_0.geometry} material={materials['movsteer_1.0.1']} />
              <mesh geometry={nodes.door_rr_movsteer_100_0.geometry} material={materials['movsteer_1.0.0']} />
              <mesh geometry={nodes.door_rr_Putih0_0.geometry} material={materials['Putih.0']} />
              <mesh geometry={nodes.door_rr_Plastic0_0.geometry} material={materials['Plastic.0']} />
              <mesh geometry={nodes.door_rr_aluminium20_0.geometry} material={materials['aluminium2.0']} />
              <mesh geometry={nodes.door_rr_dvorright0_0.geometry} material={materials['dvorright.0']} />
              <mesh geometry={nodes.door_rr_glass0_0.geometry} material={materials['glass.0']} />
              <mesh material-color={snap.items.exterior} geometry={nodes.door_rr_primary_0.geometry} material={materials.primary} />
              <mesh geometry={nodes.door_rr_primary002_0.geometry} material={materials['primary.002']} />
            </group>
            <group position={[0, 0.73, 0.57]}>
              <mesh geometry={nodes.windscreen_ok_glass0_0.geometry} material={materials['glass.0']} />
            </group>
            <group position={[0.87, 1.93, 0.13]}>
              <mesh geometry={nodes.chrome002_back_chrome_light0_0.geometry} material={materials['back_chrome_light.0']} />
              <mesh geometry={nodes.foglights_r_foglight_r_0.geometry} material={materials.foglight_r} />
              <mesh geometry={nodes.foglights_l_foglight_l_0.geometry} material={materials.foglight_l} />
              <mesh geometry={nodes.indicator_lights_r_indicator_rf_0.geometry} material={materials.indicator_rf} />
              <mesh geometry={nodes.indicator_lights_l_indicator_lf_0.geometry} material={materials.indicator_lf} />
              <mesh geometry={nodes.tembus_depan_ok_tembus_red0_0.geometry} material={materials['tembus_red.0']} />
              <mesh geometry={nodes.front_black_front_black0_0.geometry} material={materials['front_black.0']} />
              <mesh geometry={nodes.front_bumper_ok_primary_0.geometry} material={materials.primary} />
            </group>
            <group position={[0.87, -1.93, 0.28]}>
              <mesh geometry={nodes.rear_bumper_ok_primary_0.geometry} material={materials.primary} />
              <mesh geometry={nodes.light_pantulan_light_pantulan0_0.geometry} material={materials['light_pantulan.0']} />
              <mesh geometry={nodes.tembus_belakang_tembus_red0_0.geometry} material={materials['tembus_red.0']} />
              <mesh geometry={nodes.rear_bumper_movsteer_101_0.geometry} material={materials['movsteer_1.0.1']} />
            </group>
            <group position={[0, 1.33, 0.24]}>
              <mesh geometry={nodes.chrome_bonnet_ok_movsteer_101_0.geometry} material={materials['movsteer_1.0.1']} />
              <mesh geometry={nodes.bonnet_ok_primary_0.geometry} material={materials.primary} />
            </group>
            <group position={[0.93, 1.76, -0.37]}>
              <mesh geometry={nodes.wheels_wheels2_0.geometry} material={materials['wheels.2']} />
              <mesh geometry={nodes.wheels_wheels0_0.geometry} material={materials['wheels.0']} />
              <mesh geometry={nodes.wheels_wheels1_0.geometry} material={materials['wheels.1']} />
              <mesh geometry={nodes.wheels_movsteer_101_0.geometry} material={materials['movsteer_1.0.1']} />
              <mesh geometry={nodes.wheels_wheels3_0.geometry} material={materials['wheels.3']} />
              <mesh geometry={nodes.wheels_wheels4_0.geometry} material={materials['wheels.4']} />
              <mesh geometry={nodes.wheels_wheels6_0.geometry} material={materials['wheels.6']} />
              <group position={[0, -3.2, 0]} scale={1.02}>
                <mesh geometry={nodes.wheels001_wheels2_0.geometry} material={materials['wheels.2']} />
                <mesh geometry={nodes.wheels001_wheels0_0.geometry} material={materials['wheels.0']} />
                <mesh geometry={nodes.wheels001_wheels1_0.geometry} material={materials['wheels.1']} />
                <mesh geometry={nodes.wheels001_movsteer_101_0.geometry} material={materials['movsteer_1.0.1']} />
                <mesh geometry={nodes.wheels001_wheels3_0.geometry} material={materials['wheels.3']} />
                <mesh geometry={nodes.wheels001_wheels4_0.geometry} material={materials['wheels.4']} />
                <mesh geometry={nodes.wheels001_wheels6_0.geometry} material={materials['wheels.6']} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/tesla_2018_model_3.glb')
